apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-final
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jenkins-final
  template:
    metadata:
      labels:
        app: jenkins-final
    spec:
      containers:
      - name: jenkins-final
        image: public.ecr.aws/n3c9v2o9/jenkins-final:latest
        ports:
        - containerPort: 8080
