apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins_assignment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jenkins_assignment
  template:
    metadata:
      labels:
        app: jenkins_assignment
    spec:
      containers:
      - name: jenkins_assignment
        image: public.ecr.aws/n3c9v2o9/jenkins_assignment
        ports:
        - containerPort: 8080
